package enums;

public enum FacultesUSTHB {
    INFORMATIQUE,
    MATHEMATIQUES,
    PHYSIQUE,
    CHIMIE,
    BIOLOGIE,
    GEOLOGIE,
    GENIE_CIVIL,
    GENIE_ELECTRIQUE,
    GENIE_DES_PROCEDES_ET_MECANIQUE,
    ST_GAT
}
