package enums;

public enum Specialite {
    // Spécialités générales licence USTHB
    BIOLOGIE,
    CHIMIE,
    ELECTRONIQUE,
    GENIE_CIVIL,
    GENIE_MECANIQUE,
    MATHEMATIQUES,
    PHYSIQUE,
    LICENCE_INFORMATIQUE,
    SCIENCES_DE_LA_TERRE,
    GENIE_DES_PROCEDES,
    ELECTROTECHNIQUE,
    TELECOMMUNICATION,
    GEOPHYSIQUE,
    GEOLOGIE,
    AMENAGEMENT_DU_TERRITOIRE,

    // Spécialités Licence & Master Informatique USTHB
    LICENCE_ACAD,
    LICENCE_ISIL,
    LICENCE_GTR,
    MASTER_INFORMATIQUE,
    MASTER_BIO_INFO,
    MASTER_INTELLIGENCE_ARTIFICIELLE,
    MASTER_SECURITE_DES_SYSTEMES,
    MASTER_GENIE_LOGICIEL,
    MASTER_RESEAUX_ET_TELECOMMUNICATIONS,
    MASTER_BIG_DATA_ET_ANALYSE,
    MASTER_INFORMATIQUE_THEORIQUE
}
